### ISSUE TITLE
Search for only first instance of protocol separator (`://`)

### ISSUE THREAD

**Issue by samhollenbach** [lucasmlofaro/cabinets#40]
Instead of doing a split on `://`, we should do a `find` and substring around the first occurrence. While very unlikely, this will prevent paths with another occurrence of `://` from crashing cabinets.

* [Change Here](https://github.com/lucasmlofaro/cabinets/blob/main/cabinets/__init__.py#L44)

**Comment by lucasmlofaro** [comment]
Multiple occurrences of `://` should result in an `InvalidURIError` since the behavior in that case is undefined.
